number_1 = int(input("첫 번째 숫자를 입력하시오 : "))
number_2 = int(input("두 번째 숫자를 입력하시오 : "))
number_3 = int(input("세 번째 숫자를 입력하시오 : "))
avg = float((number_1 + number_2 + number_3)/3)
print(str(number_1) + " "+str(number_2) +" "+ str(number_3)+"의 평균은"+str(avg)+"입니다.")
